# Generated by Django 5.0.6 on 2024-07-28 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitness_app', '0003_alter_account_activity_level_alter_account_age_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='activity_level',
            field=models.CharField(choices=[('Sedentary', 'Sedentary'), ('Lightly Active', 'Lightly Active'), ('Moderately Active', 'Moderately Active'), ('Very Active', 'Very Active'), ('Super Active', 'Super Active')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='age',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='experience_level',
            field=models.CharField(choices=[('Beginner', 'Beginner'), ('Intermediate', 'Intermediate'), ('Advanced', 'Advanced')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='fitness_goal',
            field=models.CharField(choices=[('Lose Weight', 'Lose Weight'), ('Gain Muscle', 'Gain Muscle'), ('Maintain Fitness', 'Maintain Fitness')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='height',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='weight',
            field=models.FloatField(null=True),
        ),
    ]
