# Generated by Django 5.0.6 on 2024-07-31 19:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fitness_app', '0005_trainer_review'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trainer',
            name='available',
        ),
    ]
