# Generated by Django 5.0.6 on 2024-07-31 19:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fitness_app', '0006_remove_trainer_available'),
    ]

    operations = [
        migrations.DeleteModel(
            name='WorkoutProgram',
        ),
    ]
