# Generated by Django 5.0.7 on 2024-08-02 03:04

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fitness_app', '0007_delete_workoutprogram'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='profile_image',
            field=cloudinary.models.CloudinaryField(default='media/profile_image/default_user_image.png', max_length=255, verbose_name='image'),
        ),
        migrations.AddField(
            model_name='trainer',
            name='profile_image',
            field=cloudinary.models.CloudinaryField(default='media/profile_image/default_trainer_image.png', max_length=255, verbose_name='image'),
        ),
    ]
