# Generated by Django 5.0.7 on 2024-08-14 23:12

import cloudinary.models
import fitness_app.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fitness_app', '0010_alter_account_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='profile_image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, validators=[fitness_app.models.file_validation], verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='trainer',
            name='profile_image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, validators=[fitness_app.models.file_validation], verbose_name='image'),
        ),
    ]
