# Generated by Django 5.0.7 on 2024-08-17 13:54

import cloudinary.models
import fitness_app.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fitness_app', '0011_alter_account_profile_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise',
            name='image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, validators=[fitness_app.models.file_validation], verbose_name='image'),
        ),
    ]
